---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: test-new-vm-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: create-vm-vpshere
  extra_vars: 